server:
  port: 8083


#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: rest-client


eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka,http://localhost:8762/eureka

logging:
  level:
    com.example.howtodoinjava: DEBUG