server:
  port: 8082


#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: initial-server


eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka:8761/eureka

logging:
  level:
    com.example.howtodoinjava: DEBUG
